export const appConfig = {
  features: {
    editableUsers: true,
    deletableUsers: true,
  },
  validation: {
    name: {
      minLength: 3,
      maxLength: 50,
      required: true,
    },
    email: {
      required: true,
      pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    },
    linkedinUrl: {
      required: true,
      pattern: /^(https?:\/\/)?(www\.)?linkedin\.com\/(in|company)\/[\w-]+/i,
    },
    pin: {
      required: true,
      length: 6,
      pattern: /^\d{6}$/,
    },
  },
  text: {
    pageTitle: "User Management",
    pageSubtitle:
      "Allows administrators to view, add, edit, and delete user details within the system",
    addUserButton: "Add User",
    editButton: "Edit",
    deleteButton: "Delete",
    cancelButton: "Cancel",
    noUsersFound: "No users found",
    noUsersSubtext: "Click Add User to create",
    showingUsers: "Showing",
    user: "user",
    users: "users",
    loading: "Loading...",
    deleteConfirmTitle: "Delete User",
    deleteConfirmMessage: "Are you sure you want to delete",
    addUserTitle: "Add New User",
    editUserTitle: "Edit User",
    updateButton: "Update User",
    viewProfile: "View Profile",
    completeAddress: "Complete Address",
    pin: "PIN",
    formFields: {
      name: "Name",
      email: "Email",
      linkedinUrl: "LinkedIn URL",
      gender: "Gender",
      addressLine1: "Address Line 1",
      addressLine2: "Address Line 2",
      state: "State",
      city: "City",
      pinCode: "PIN Code",
    },
    placeholders: {
      name: "Enter full name",
      email: "example@email.com",
      linkedinUrl: "https://linkedin.com/in/username",
      gender: "Select Gender",
      addressLine1: "Enter address",
      addressLine2: "Optional",
      state: "Select State",
      city: "Select City",
      pinCode: "6-digit PIN",
    },
    genderOptions: {
      male: "Male",
      female: "Female",
      other: "Other",
    },
    errors: {
      required: "Required",
      invalidEmail: "Invalid email",
      invalidUrl: "Invalid LinkedIn URL",
      duplicateEmail: "Email already exists",
      minChars: "Min",
      maxChars: "Max",
      chars: "chars",
      digits: "6 digits required",
    },
    tableHeaders: {
      name: "Name",
      email: "Email",
      linkedin: "LinkedIn",
      gender: "Gender",
      address: "Address",
      actions: "Actions",
    },
    addressLabels: {
      line1: "Line 1",
      line2: "Line 2",
      city: "City",
      state: "State",
      pin: "PIN",
      notAvailable: "N/A",
    },
  },
};
